Verify wixl installation and fallback to wixl package if needed

diff --git a/.github/workflows/v2.yml b/.github/workflows/v2.yml
--- a/.github/workflows/v2.yml
+++ b/.github/workflows/v2.yml
@@ -27,6 +27,8 @@ jobs:
         run: |
           sudo apt-get update -q
           sudo apt-get install -y gcc-multilib gcc-mingw-w64 msitools
+          which wixl || (echo "wixl not found in msitools, trying wixl package" && sudo apt-get install -y wixl)
+          wixl --version
 
       - name: "Run tests"
         run: "make test"
